export const Users = [
  {
    id: 1,
    profilePicture: "people/1.jpeg",
    username: "The Queen",
  },
  {
    id: 2,
    profilePicture: "people/2.jpeg",
    username: "Jack Defender",
  },
  {
    id: 3,
    profilePicture: "people/3.jpeg",
    username: "John Pathfinder",
  },
  {
    id: 4,
    profilePicture: "people/4.jpeg",
    username: "Selby Pollenprocurer",
  },
  {
    id: 5,
    profilePicture: "people/5.jpeg",
    username: "Darby Pollenlover",
  },
  {
    id: 6,
    profilePicture: "people/6.jpeg",
    username: "Crosby Flowerfinder",
  },
  {
    id: 7,
    profilePicture: "people/7.jpeg",
    username: "Joby Tastetester",
  },
  {
    id: 8,
    profilePicture: "people/8.jpeg",
    username: "Toby Hivemaster",
  },
  {
    id: 9,
    profilePicture: "people/9.jpeg",
    username: "Colby Stronghive",
  },
  {
    id: 10,
    profilePicture: "people/10.jpeg",
    username: "Robbie Yellowcomb",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Look at this flower I found!!!!",
    photo: "posts/1.jpeg",
    date: "4 mins ago",
    userId: 1,
    like: 36,
    comment: 11,
  },
  {
    id: 2,
    photo: "posts/2.jpeg",
    date: "16 mins ago",
    userId: 2,
    like: 3,
    comment: 1,
  },
  {
    id: 3,
    desc: "Traffic congestion problems at hive 4!",
    photo: "posts/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 54,
    comment: 14,
  },
  {
    id: 4,
    photo: "posts/4.jpeg",
    date: "3 hours ago",
    userId: 4,
    like: 5,
    comment: 1,
  },
  {
    id: 5,
    photo: "posts/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 25,
    comment: 3,
  },
  {
    id: 6,
    photo: "posts/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 42,
    comment: 7,
  },
  {
    id: 7,
    desc: "Honey leakage! Be careful!",
    photo: "posts/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 72,
    comment: 9,
  },
  {
    id: 8,
    photo: "posts/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 14,
    comment: 2,
  },
  {
    id: 9,
    desc: "1 week vacation for any Bee who finds this flower!",
    photo: "posts/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 42,
    comment: 19,
  },
  {
    id: 10,
    photo: "posts/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 10,
    comment: 3,
  },
];
